mongodb:
  cv:
    host: localhost
    port: 27017
    database: mednean_cv
  kl:
    host: localhost
    port: 27017
    database: mednean_kl
  mg:
    host: localhost
    port: 27017
    database: mednean_mg
