mongodb:
  cv:
    host: localhost
    port: 27017
    database: mednean_cv
  kl:
    host: localhost
    port: 27017
    database: mednean_kl
  mg:
    host: localhost
    port: 27017
    database: mednean_mg
  bs:
    host: localhost
    port: 27017
    database: mednean_bs


spring.freemarker.suffix: .ftl

server:
  port: 8055
