


mongodb:
  primary:
    host: localhost
    port: 27017
    database: mednean_cv
  secondary:
    host: localhost
    port: 27017
    database: mednean_kl
  tertiary:
    host: localhost
    port: 27017
    database: mednean_mg


